// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: Classes.proto

package Deviant

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Classes int32

const (
	Classes_WARRIOR Classes = 0
	Classes_MAGE    Classes = 1
	Classes_PRIEST  Classes = 2
)

// Enum value maps for Classes.
var (
	Classes_name = map[int32]string{
		0: "WARRIOR",
		1: "MAGE",
		2: "PRIEST",
	}
	Classes_value = map[string]int32{
		"WARRIOR": 0,
		"MAGE":    1,
		"PRIEST":  2,
	}
)

func (x Classes) Enum() *Classes {
	p := new(Classes)
	*p = x
	return p
}

func (x Classes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Classes) Descriptor() protoreflect.EnumDescriptor {
	return file_Classes_proto_enumTypes[0].Descriptor()
}

func (Classes) Type() protoreflect.EnumType {
	return &file_Classes_proto_enumTypes[0]
}

func (x Classes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Classes.Descriptor instead.
func (Classes) EnumDescriptor() ([]byte, []int) {
	return file_Classes_proto_rawDescGZIP(), []int{0}
}

var File_Classes_proto protoreflect.FileDescriptor

var file_Classes_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x44, 0x65, 0x76, 0x69, 0x61, 0x6e, 0x74, 0x2a, 0x2c, 0x0a, 0x07, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x65, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x41, 0x52, 0x52, 0x49, 0x4f, 0x52, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x4d, 0x41, 0x47, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x52,
	0x49, 0x45, 0x53, 0x54, 0x10, 0x02, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Classes_proto_rawDescOnce sync.Once
	file_Classes_proto_rawDescData = file_Classes_proto_rawDesc
)

func file_Classes_proto_rawDescGZIP() []byte {
	file_Classes_proto_rawDescOnce.Do(func() {
		file_Classes_proto_rawDescData = protoimpl.X.CompressGZIP(file_Classes_proto_rawDescData)
	})
	return file_Classes_proto_rawDescData
}

var file_Classes_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Classes_proto_goTypes = []interface{}{
	(Classes)(0), // 0: Deviant.Classes
}
var file_Classes_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Classes_proto_init() }
func file_Classes_proto_init() {
	if File_Classes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Classes_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Classes_proto_goTypes,
		DependencyIndexes: file_Classes_proto_depIdxs,
		EnumInfos:         file_Classes_proto_enumTypes,
	}.Build()
	File_Classes_proto = out.File
	file_Classes_proto_rawDesc = nil
	file_Classes_proto_goTypes = nil
	file_Classes_proto_depIdxs = nil
}
