// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: EncounterRequest.proto

package Deviant

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type EntityActionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action *EntityAction `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
}

func (x *EntityActionRequest) Reset() {
	*x = EntityActionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_EncounterRequest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityActionRequest) ProtoMessage() {}

func (x *EntityActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_EncounterRequest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityActionRequest.ProtoReflect.Descriptor instead.
func (*EntityActionRequest) Descriptor() ([]byte, []int) {
	return file_EncounterRequest_proto_rawDescGZIP(), []int{0}
}

func (x *EntityActionRequest) GetAction() *EntityAction {
	if x != nil {
		return x.Action
	}
	return nil
}

// The request message containing the user's name.
type EncounterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player string `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *EncounterRequest) Reset() {
	*x = EncounterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_EncounterRequest_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncounterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncounterRequest) ProtoMessage() {}

func (x *EncounterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_EncounterRequest_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncounterRequest.ProtoReflect.Descriptor instead.
func (*EncounterRequest) Descriptor() ([]byte, []int) {
	return file_EncounterRequest_proto_rawDescGZIP(), []int{1}
}

func (x *EncounterRequest) GetPlayer() string {
	if x != nil {
		return x.Player
	}
	return ""
}

// The response message containing the greetings
type EncounterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Encounter *Encounter `protobuf:"bytes,1,opt,name=encounter,proto3" json:"encounter,omitempty"`
}

func (x *EncounterResponse) Reset() {
	*x = EncounterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_EncounterRequest_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncounterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncounterResponse) ProtoMessage() {}

func (x *EncounterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_EncounterRequest_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncounterResponse.ProtoReflect.Descriptor instead.
func (*EncounterResponse) Descriptor() ([]byte, []int) {
	return file_EncounterRequest_proto_rawDescGZIP(), []int{2}
}

func (x *EncounterResponse) GetEncounter() *Encounter {
	if x != nil {
		return x.Encounter
	}
	return nil
}

var File_EncounterRequest_proto protoreflect.FileDescriptor

var file_EncounterRequest_proto_rawDesc = []byte{
	0x0a, 0x16, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x44, 0x65, 0x76, 0x69, 0x61, 0x6e,
	0x74, 0x1a, 0x0f, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x12, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x13, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x44, 0x65, 0x76, 0x69, 0x61, 0x6e, 0x74, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2a, 0x0a, 0x10,
	0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x45, 0x0a, 0x11, 0x45, 0x6e, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a,
	0x09, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x61, 0x6e, 0x74, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x52, 0x09, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x32,
	0xf4, 0x01, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x12, 0x49, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x12, 0x19, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x61, 0x6e, 0x74, 0x2e, 0x45, 0x6e, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x44, 0x65, 0x76, 0x69, 0x61, 0x6e, 0x74, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x12, 0x4d, 0x0a, 0x0f, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x1a,
	0x2e, 0x44, 0x65, 0x76, 0x69, 0x61, 0x6e, 0x74, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x1a, 0x2e, 0x44, 0x65, 0x76,
	0x69, 0x61, 0x6e, 0x74, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x12, 0x4a, 0x0a, 0x0a, 0x54, 0x61,
	0x6b, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x61,
	0x6e, 0x74, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x61, 0x6e, 0x74,
	0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_EncounterRequest_proto_rawDescOnce sync.Once
	file_EncounterRequest_proto_rawDescData = file_EncounterRequest_proto_rawDesc
)

func file_EncounterRequest_proto_rawDescGZIP() []byte {
	file_EncounterRequest_proto_rawDescOnce.Do(func() {
		file_EncounterRequest_proto_rawDescData = protoimpl.X.CompressGZIP(file_EncounterRequest_proto_rawDescData)
	})
	return file_EncounterRequest_proto_rawDescData
}

var file_EncounterRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_EncounterRequest_proto_goTypes = []interface{}{
	(*EntityActionRequest)(nil), // 0: Deviant.EntityActionRequest
	(*EncounterRequest)(nil),    // 1: Deviant.EncounterRequest
	(*EncounterResponse)(nil),   // 2: Deviant.EncounterResponse
	(*EntityAction)(nil),        // 3: Deviant.EntityAction
	(*Encounter)(nil),           // 4: Deviant.Encounter
}
var file_EncounterRequest_proto_depIdxs = []int32{
	3, // 0: Deviant.EntityActionRequest.action:type_name -> Deviant.EntityAction
	4, // 1: Deviant.EncounterResponse.encounter:type_name -> Deviant.Encounter
	1, // 2: Deviant.GetEncounter.StartEncounter:input_type -> Deviant.EncounterRequest
	2, // 3: Deviant.GetEncounter.UpdateEncounter:input_type -> Deviant.EncounterResponse
	0, // 4: Deviant.GetEncounter.TakeAction:input_type -> Deviant.EntityActionRequest
	2, // 5: Deviant.GetEncounter.StartEncounter:output_type -> Deviant.EncounterResponse
	2, // 6: Deviant.GetEncounter.UpdateEncounter:output_type -> Deviant.EncounterResponse
	2, // 7: Deviant.GetEncounter.TakeAction:output_type -> Deviant.EncounterResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_EncounterRequest_proto_init() }
func file_EncounterRequest_proto_init() {
	if File_EncounterRequest_proto != nil {
		return
	}
	file_Encounter_proto_init()
	file_EntityAction_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_EncounterRequest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityActionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_EncounterRequest_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncounterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_EncounterRequest_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncounterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_EncounterRequest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_EncounterRequest_proto_goTypes,
		DependencyIndexes: file_EncounterRequest_proto_depIdxs,
		MessageInfos:      file_EncounterRequest_proto_msgTypes,
	}.Build()
	File_EncounterRequest_proto = out.File
	file_EncounterRequest_proto_rawDesc = nil
	file_EncounterRequest_proto_goTypes = nil
	file_EncounterRequest_proto_depIdxs = nil
}
