// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: Encounter.proto

package Deviant

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Encounter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Completed         bool     `protobuf:"varint,2,opt,name=completed,proto3" json:"completed,omitempty"`
	Board             *Board   `protobuf:"bytes,3,opt,name=board,proto3" json:"board,omitempty"`
	Turn              *Turn    `protobuf:"bytes,4,opt,name=turn,proto3" json:"turn,omitempty"`
	ActiveEntityOrder []string `protobuf:"bytes,5,rep,name=activeEntityOrder,proto3" json:"activeEntityOrder,omitempty"`
	ActiveEntity      *Entity  `protobuf:"bytes,6,opt,name=activeEntity,proto3" json:"activeEntity,omitempty"`
}

func (x *Encounter) Reset() {
	*x = Encounter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Encounter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Encounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Encounter) ProtoMessage() {}

func (x *Encounter) ProtoReflect() protoreflect.Message {
	mi := &file_Encounter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Encounter.ProtoReflect.Descriptor instead.
func (*Encounter) Descriptor() ([]byte, []int) {
	return file_Encounter_proto_rawDescGZIP(), []int{0}
}

func (x *Encounter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Encounter) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *Encounter) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *Encounter) GetTurn() *Turn {
	if x != nil {
		return x.Turn
	}
	return nil
}

func (x *Encounter) GetActiveEntityOrder() []string {
	if x != nil {
		return x.ActiveEntityOrder
	}
	return nil
}

func (x *Encounter) GetActiveEntity() *Entity {
	if x != nil {
		return x.ActiveEntity
	}
	return nil
}

var File_Encounter_proto protoreflect.FileDescriptor

var file_Encounter_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x44, 0x65, 0x76, 0x69, 0x61, 0x6e, 0x74, 0x1a, 0x0b, 0x42, 0x6f, 0x61, 0x72,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x54, 0x75, 0x72, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xe5, 0x01, 0x0a, 0x09, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x24, 0x0a,
	0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x44,
	0x65, 0x76, 0x69, 0x61, 0x6e, 0x74, 0x2e, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x05, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x12, 0x21, 0x0a, 0x04, 0x74, 0x75, 0x72, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x61, 0x6e, 0x74, 0x2e, 0x54, 0x75, 0x72, 0x6e,
	0x52, 0x04, 0x74, 0x75, 0x72, 0x6e, 0x12, 0x2c, 0x0a, 0x11, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x11, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x44, 0x65, 0x76,
	0x69, 0x61, 0x6e, 0x74, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x0c, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_Encounter_proto_rawDescOnce sync.Once
	file_Encounter_proto_rawDescData = file_Encounter_proto_rawDesc
)

func file_Encounter_proto_rawDescGZIP() []byte {
	file_Encounter_proto_rawDescOnce.Do(func() {
		file_Encounter_proto_rawDescData = protoimpl.X.CompressGZIP(file_Encounter_proto_rawDescData)
	})
	return file_Encounter_proto_rawDescData
}

var file_Encounter_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Encounter_proto_goTypes = []interface{}{
	(*Encounter)(nil), // 0: Deviant.Encounter
	(*Board)(nil),     // 1: Deviant.Board
	(*Turn)(nil),      // 2: Deviant.Turn
	(*Entity)(nil),    // 3: Deviant.Entity
}
var file_Encounter_proto_depIdxs = []int32{
	1, // 0: Deviant.Encounter.board:type_name -> Deviant.Board
	2, // 1: Deviant.Encounter.turn:type_name -> Deviant.Turn
	3, // 2: Deviant.Encounter.activeEntity:type_name -> Deviant.Entity
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_Encounter_proto_init() }
func file_Encounter_proto_init() {
	if File_Encounter_proto != nil {
		return
	}
	file_Board_proto_init()
	file_Entity_proto_init()
	file_Turn_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_Encounter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Encounter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Encounter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Encounter_proto_goTypes,
		DependencyIndexes: file_Encounter_proto_depIdxs,
		MessageInfos:      file_Encounter_proto_msgTypes,
	}.Build()
	File_Encounter_proto = out.File
	file_Encounter_proto_rawDesc = nil
	file_Encounter_proto_goTypes = nil
	file_Encounter_proto_depIdxs = nil
}
