// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: Tiles.proto

package Deviant

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Tiles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tiles []*TilesRow `protobuf:"bytes,1,rep,name=tiles,proto3" json:"tiles,omitempty"`
}

func (x *Tiles) Reset() {
	*x = Tiles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Tiles_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tiles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tiles) ProtoMessage() {}

func (x *Tiles) ProtoReflect() protoreflect.Message {
	mi := &file_Tiles_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tiles.ProtoReflect.Descriptor instead.
func (*Tiles) Descriptor() ([]byte, []int) {
	return file_Tiles_proto_rawDescGZIP(), []int{0}
}

func (x *Tiles) GetTiles() []*TilesRow {
	if x != nil {
		return x.Tiles
	}
	return nil
}

var File_Tiles_proto protoreflect.FileDescriptor

var file_Tiles_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x54, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x44,
	0x65, 0x76, 0x69, 0x61, 0x6e, 0x74, 0x1a, 0x0e, 0x54, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x6f, 0x77,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x05, 0x54, 0x69, 0x6c, 0x65, 0x73, 0x12,
	0x27, 0x0a, 0x05, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x44, 0x65, 0x76, 0x69, 0x61, 0x6e, 0x74, 0x2e, 0x54, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x6f,
	0x77, 0x52, 0x05, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Tiles_proto_rawDescOnce sync.Once
	file_Tiles_proto_rawDescData = file_Tiles_proto_rawDesc
)

func file_Tiles_proto_rawDescGZIP() []byte {
	file_Tiles_proto_rawDescOnce.Do(func() {
		file_Tiles_proto_rawDescData = protoimpl.X.CompressGZIP(file_Tiles_proto_rawDescData)
	})
	return file_Tiles_proto_rawDescData
}

var file_Tiles_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Tiles_proto_goTypes = []interface{}{
	(*Tiles)(nil),    // 0: Deviant.Tiles
	(*TilesRow)(nil), // 1: Deviant.TilesRow
}
var file_Tiles_proto_depIdxs = []int32{
	1, // 0: Deviant.Tiles.tiles:type_name -> Deviant.TilesRow
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Tiles_proto_init() }
func file_Tiles_proto_init() {
	if File_Tiles_proto != nil {
		return
	}
	file_TilesRow_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_Tiles_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tiles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Tiles_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Tiles_proto_goTypes,
		DependencyIndexes: file_Tiles_proto_depIdxs,
		MessageInfos:      file_Tiles_proto_msgTypes,
	}.Build()
	File_Tiles_proto = out.File
	file_Tiles_proto_rawDesc = nil
	file_Tiles_proto_goTypes = nil
	file_Tiles_proto_depIdxs = nil
}
