version: "3"

services:
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
  instance_shard:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        LOGGER_TYPE: ${LOGGER_TYPE}
    ports:
      - 50051:50051
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOGGER_TYPE
    links:
      - redis
    depends_on:
      - redis
