name: Go

on:
  push:
    branches: [ master, ghost15_test ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out Instance Shard into the Go module directory
      uses: actions/checkout@v2

    - name: Check out Protobuf into Go module directory
      uses: actions/checkout@v2
      with:
        repository: recluse-games/deviant-protobuf
        token: ${{ secrets.CI_ROBOT }}

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: |
        go build -v ./...

    - name: Test
      run: go test -v ./...
    
    # Create Artifact Upload Directory
    - run: mkdir -p recluse-games/deviant-instance-shard/build

    - run: pwd && ls && ls ..

    # Copy Build Artifact to Artifact Upload Directory
    - run: cp deviant-instance-shard recluse-games/deviant-instance-shard/build/deviant-instance-shard
  
    # Publish Uploaded Artifact
    - uses: actions/upload-artifact@v2
      with:
        name: deviant-instance-shard
        path: recluse-games/deviant-instance-shard/build/deviant-instance-shard
