name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: configure-git
        run: |
          RUN git config --global url."https://$GITHUB_TOKEN:x-oauth-basic@github.com".insteadOf "https://github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.CI_ROBOT_SECRET }}
          GOPRIVATE: "github.com/recluse-games"
          GIT_TERMINAL_PROMPT: 1
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.26
  build:
    needs: lint
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Install Dependencies
      run: sudo apt -y install build-essential 
      
    - name: Set up .netrc file
      run: echo "machine github.com login recluse-ci-robot password $CI_ROBOT_SECRET" > $HOME/.netrc
      env:
        CI_ROBOT_SECRET: ${{ secrets.CI_ROBOT }}

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out Instance Shard into the Go module directory
      uses: actions/checkout@v2
      with:
        path: go/src/github.com/recluse-games/deviant-instance-shard

    - name: Check out Protobuf into Go module directory
      uses: actions/checkout@v2
      with:
        repository: recluse-games/deviant-protobuf
        token: ${{ secrets.CI_ROBOT }}
        path: go/src/github.com/recluse-games/deviant-protobuf
      
    - name: Build deviant-instance-shard
      run: |
        make
      working-directory: go/src/github.com/recluse-games/deviant-instance-shard
      env:
        GOPATH: ${{ github.workspace }}/go
        GOPRIVATE: "github.com/recluse-games"

    - name: Publish Artifacts
      uses: actions/upload-artifact@v2
      with:
        path: go/src/github.com/recluse-games/deviant-instance-shard/bin/*
