name: Build/Publish

on:
  push:
    branches: 
        - master

jobs:
  build-publish:
    name: build
    runs-on: ubuntu-latest

    steps: 
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: reclusegames/deviant-instance-shard
        tags: latest
        build_args: GITHUB_TOKEN=${{ secrets.RECLUSE_CI_ROBOT_TOKEN }}
        dockerfile: ${{ github.workspace }}/Dockerfile 
        path: ${{ github.workspace }}